This model creates a projected value for a given statistic by using a mean of the previous three seasons for each player.
There is no projection for first year players.

# Import Packages and Data

In [2]:
# Import necessary libraries
import pandas as pd
pd.set_option('display.max_columns', None)
import sys
import os

sys.path.append(os.path.abspath(".."))  
from Resources.properly_format_data import GetData

In [3]:
# Combine lists of plate appearance stats and non-plate appearance stats
non_pa_list = ['G', 'AB', 'PA', 'AVG', 'BB%', 'OBP', 'SLG', 'OPS', 'ISO', 'wOBA', 'wRAA', 'wRC+', 'BB%+']
pa_list = ['H', '1B', '2B', '3B', 'HR', 'R', 'RBI', 'BB', 'SH', 'SB']
labels = ['IDfg', 'Season', 'Name', 'Team', 'Age']
combined_list = pa_list

In [4]:
data_set = GetData(2025, 2025, non_pa_list, pa_list, labels)

In [5]:
formatted_df = data_set.format_data_for_models(add_2026=False)

c:\Users\tomba\work application folder\baseball_projection\Resources\properly_format_data.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['IDfg'] = filtered_df['IDfg'].astype(str)

In [6]:
df = data_set.starting_data[labels]
df = df[df['Season'] == 2025]

In [7]:
prev_seasons = data_set.starting_data[data_set.starting_data['Season']!= 2025]

In [8]:
for stat in pa_list:
    avgs = prev_seasons.groupby('IDfg')[stat].mean()
    df = df.merge(avgs, on='IDfg', how='left')

In [9]:
df

,IDfg,Season,Name,Team,Age,H,1B,2B,3B,HR,R,RBI,BB,SH,SB
0,15640,2025,Aaron Judge,NYY,33,151.666667,72.333333,26.666667,0.333333,52.333333,111.333333,116.666667,110.666667,0.000000,9.666667
1,21534,2025,Cal Raleigh,SEA,28,105.666667,55.000000,19.666667,0.666667,30.333333,65.666667,79.333333,54.000000,0.000000,2.333333
2,25764,2025,Bobby Witt Jr.,KCR,25,179.333333,108.000000,34.666667,9.333333,27.333333,101.333333,95.000000,42.333333,0.333333,36.666667
3,19755,2025,Shohei Ohtani,LAD,30,169.333333,87.000000,31.333333,7.000000,44.000000,108.666667,106.666667,81.333333,0.000000,30.000000
4,22799,2025,Geraldo Perdomo,ARI,25,92.000000,67.666667,17.000000,2.666667,4.666667,63.333333,41.333333,50.000000,11.000000,11.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,19734,2025,Josh Rojas,CHW,31,97.000000,68.666667,20.333333,1.000000,7.000000,53.666667,42.333333,42.666667,2.666667,15.000000
457,13723,2025,Jacob Stallings,- - -,35,62.333333,42.333333,14.333333,0.333333,5.333333,26.000000,30.000000,27.666667,1.666667,0.000000
458,35041,2025,Jac Caglianone,KCR,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,18126,2025,LaMonte Wade Jr.,- - -,31,80.333333,56.000000,12.333333,1.000000,11.000000,46.000000,35.000000,54.666667,2.333333,1.666667
460,25845,2025,Michael Toglia,COL,26,44.666667,23.666667,9.000000,1.666667,10.333333,30.000000,25.333333,24.333333,0.000000,4.000000

In [10]:
df.to_csv('../other_model_comparisons_2025/model_one.csv')

In [11]:
data_set.starting_data.groupby('IDfg')['H'].mean()

IDfg
1177      83.000000
1744      93.500000
2136      91.666667
2396     108.500000
2434      70.000000
            ...
34979     32.000000
35041     33.000000
35108    104.000000
35110    122.000000
35322     45.000000
Name: H, Length: 738, dtype: float64

In [12]:
# Filter the DataFrame to include only the specified columns
df = df.loc[:, filtered_list]

NameError: name 'filtered_list' is not defined

In [ ]:
# Combine lists of plate appearance stats and non-plate appearance stats
combined_stats = pa_list + non_pa_list

# Automate

In [ ]:
def add_projected_values(dataframe, stat):
    """
    Adds a projected value for a given statistic to the DataFrame using a rolling mean 
    of the previous three seasons for each player.
    
    Args:
        dataframe (pd.DataFrame): The input DataFrame containing player statistics.
        stat (str): The name of the statistic to project.

    Returns:
        pd.DataFrame: The DataFrame with a new column for the projected statistic.
    """
    # Add league average for the given statistic to the DataFrame
    dataframe = dataframe.sort_values(by=['Name', 'Season'], ascending=[True, True])

    # Use vectorized rolling mean with groupby
    dataframe[f"Projected_{stat}"] = (
        dataframe.groupby('Name')[stat]    # Group by player
        .shift()                           # Shift to exclude the current season
        .rolling(window=3, min_periods=0)  # Rolling mean with up to 3 previous seasons
        .mean()                            # Compute the mean for the rolling window
    )

    return dataframe

# Loop through a list of statistics and apply the add_projected_values function to each one
for value in pa_list:
    df = add_projected_values(formatted_df, value)

In [ ]:
df

,IDfg,Season,Name,Team,Age,H,1B,2B,3B,HR,R,RBI,BB,SH,SB,G,AB,PA,AVG,BB%,OBP,SLG,OPS,ISO,wOBA,wRAA,wRC+,BB%+,1Prev_H,1Prev_1B,1Prev_2B,1Prev_3B,1Prev_HR,1Prev_R,1Prev_RBI,1Prev_BB,1Prev_SH,1Prev_SB,1Prev_G,1Prev_AB,1Prev_PA,1Prev_AVG,1Prev_BB%,1Prev_OBP,1Prev_SLG,1Prev_OPS,1Prev_ISO,1Prev_wOBA,1Prev_wRAA,1Prev_wRC+,1Prev_BB%+,2Prev_H,2Prev_1B,2Prev_2B,2Prev_3B,2Prev_HR,2Prev_R,2Prev_RBI,2Prev_BB,2Prev_SH,2Prev_SB,2Prev_G,2Prev_AB,2Prev_PA,2Prev_AVG,2Prev_BB%,2Prev_OBP,2Prev_SLG,2Prev_OPS,2Prev_ISO,2Prev_wOBA,2Prev_wRAA,2Prev_wRC+,2Prev_BB%+,3Prev_H,3Prev_1B,3Prev_2B,3Prev_3B,3Prev_HR,3Prev_R,3Prev_RBI,3Prev_BB,3Prev_SH,3Prev_SB,3Prev_G,3Prev_AB,3Prev_PA,3Prev_AVG,3Prev_BB%,3Prev_OBP,3Prev_SLG,3Prev_OPS,3Prev_ISO,3Prev_wOBA,3Prev_wRAA,3Prev_wRC+,3Prev_BB%+,Prev_League_Avg_H,Prev_League_Avg_1B,Prev_League_Avg_2B,Prev_League_Avg_3B,Prev_League_Avg_HR,Prev_League_Avg_R,Prev_League_Avg_RBI,Prev_League_Avg_BB,Prev_League_Avg_SH,Prev_League_Avg_SB,Prev_League_Avg_G,Prev_League_Avg_AB,Prev_League_Avg_PA,Prev_League_Avg_AVG,Prev_League_Avg_BB%,Prev_League_Avg_OBP,Prev_League_Avg_SLG,Prev_League_Avg_OPS,Prev_League_Avg_ISO,Prev_League_Avg_wOBA,Prev_League_Avg_wRAA,Prev_League_Avg_wRC+,Prev_League_Avg_BB%+,Projected_SB
423,15640,2025,Aaron Judge,NYY,33,179,94,30,2,53,137,114,124,0,12,152,541,679,0.331,0.183,0.457,0.688,1.144,0.357,0.463,82.5,204,221,180.0,85.0,36.0,1.0,58.0,122.0,144.0,133.0,0.0,10.0,158.0,559.0,704.0,0.322,0.189,0.458,0.701,1.159,0.379,0.476,93.8,220.0,233.0,98.0,45.0,16.0,0.0,37.0,79.0,75.0,88.0,0.0,3.0,106.0,367.0,458.0,0.267,0.192,0.406,0.613,1.019,0.346,0.420,38.8,173.0,229.0,177.0,87.0,28.0,0.0,62.0,133.0,131.0,111.0,0.0,16.0,157.0,570.0,696.0,0.311,0.159,0.425,0.686,1.111,0.375,0.458,82.1,206.0,200.0,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
911,19844,2025,Abraham Toro,BOS,28,62,42,13,0,7,33,27,14,0,2,77,259,284,0.239,0.049,0.289,0.371,0.659,0.131,0.286,-6.3,77,60,81.0,57.0,17.0,1.0,6.0,34.0,26.0,20.0,2.0,4.0,94.0,337.0,364.0,0.240,0.055,0.293,0.350,0.643,0.110,0.283,-8.0,87.0,68.0,60.0,36.0,13.0,1.0,10.0,36.0,35.0,22.0,0.0,2.0,109.0,324.0,352.0,0.185,0.063,0.239,0.324,0.563,0.139,0.246,-17.7,63.0,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
1580,27962,2025,Adael Amador,COL,22,20,12,7,0,1,5,10,11,3,1,41,113,128,0.177,0.086,0.256,0.265,0.521,0.088,0.238,-7.8,35,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
386,15223,2025,Adam Frazier,- - -,33,112,85,20,0,7,43,44,26,1,8,134,419,459,0.267,0.057,0.319,0.365,0.684,0.098,0.300,-5.0,89,67,53.0,38.0,10.0,1.0,4.0,35.0,22.0,22.0,3.0,3.0,104.0,262.0,294.0,0.202,0.075,0.282,0.294,0.576,0.092,0.261,-11.6,65.0,92.0,99.0,63.0,21.0,2.0,13.0,59.0,60.0,32.0,4.0,11.0,141.0,412.0,455.0,0.240,0.070,0.300,0.396,0.696,0.155,0.302,-6.0,92.0,84.0,129.0,100.0,22.0,4.0,3.0,61.0,42.0,46.0,4.0,11.0,156.0,541.0,602.0,0.238,0.076,0.301,0.311,0.612,0.072,0.274,-17.3,82.0,96.0,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
1327,24598,2025,Addison Barger,TOR,25,112,58,32,1,21,61,74,36,0,4,135,460,502,0.243,0.072,0.301,0.454,0.756,0.211,0.322,3.5,107,87,41.0,23.0,11.0,0.0,7.0,20.0,28.0,14.0,0.0,2.0,69.0,208.0,225.0,0.197,0.062,0.250,0.351,0.601,0.154,0.262,-8.6,69.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,19556,2025,Yordan Alvarez,HOU,28,45,31,8,0,6,17,27,28,0,1,48,165,199,0.273,0.141,0.367,0.430,0.797,0.158,0.338,4.0,118,170,170.0,99.0,34.0,2.0,35.0,88.0,86.0,69.0,0.0,6.0,147.0,552.0,635.0,0.308,0.109,0.392,0.567,0.959,0.259,0.402,46.7,167.0,134.0,120.0,64.0,24.0,1.0,31.0,77.0,97.0,69.0,0.0,0.0,114.0,410.0,496.0,0.293,0.139,0.407,0.583,0.990,0.290,0.415,40.0,170.0,166.0,144.0,76.0,29.0,2.0,37.0,95.0,97.0,78.0,0.0,1.0,135.0,470.0,561.0,0.306,0.139,0.406,0.613,1.019,0.306,0.427,52.1,185.0,175.0,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
1672,31562,2025,Zach Dezenzo,HOU,25,24,16,6,0,2,17,10,11,0,1,34,98,109,0.245,0.101,0.321,0.367,0.688,0.122,0.306,-0.7,96,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
830,19392,2025,Zach McKinstry,DET,30,117,71,23,11,12,68,49,46,1,19,144,452,511,0.259,0.090,0.333,0.438,0.771,0.179,0.333,8.3,114,109,64.0,41.0,14.0,5.0,4.0,32.0,23.0,24.0,0.0,16.0,118.0,297.0,325.0,0.215,0.074,0.277,0.337,0.614,0.121,0.270,-10.4,74.0,91.0,107.0,73.0,21.0,4.0,9.0,60.0,35.0,44.0,2.0,16.0,148.0,464.0,518.0,0.231,0.085,0.302,0.351,0.654,0.121,0.289,-12.7,81.0,101.0,33.0,19.0,6.0,3.0,5.0,21.0,14.0,16.0,2.0,7.0,57.0,166.0,185.0,0.199,0.086,0.273,0.361,0.635,0.163,0.280,-4.4,81.0,104.0,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
1657,31347,2025,Zach Neto,LAA,24,129,73,29,1,26,82,62,33,2,26,128,502,554,0.257,0.060,0.319,0.474,0.793,0.217,0.337,10.8,116,72,135.0,77.0,34.0,1.0,23.0,70.0,77.0,39.0,4.0,30.0,155.0,542.0,602.0,0.249,0.065,0.318,0.443,0.761,0.194,0.330,9.6,115.0,80.0,65.0,39.0,17.0,0.0,9.0,38.0,34.0,20.0,1.0,5.0,84.0,289.0,329.0,0.225,0.061,0.308,0.377,0.685,0.152,0.302,-4.4,89.0,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN
1631,29766,2025,Zack Gelof,ATH,25,16,11,3,0,2,12,7,7,1,1,30,92,101,0.174,0.069,0.230,0.272,0.502,0.098,0.224,-7.3,36,84,105.0,66.0,20.0,2.0,17.0,60.0,49.0,38.0,3.0,25.0,138.0,497.0,547.0,0.211,0.069,0.270,0.362,0.632,0.151,0.276,-14.9,82.0,86.0,72.0,37.0,20.0,1.0,14.0,40.0,32.0,26.0,0.0,14.0,69.0,270.0,300.0,0.267,0.087,0.337,0.504,0.840,0.237,0.357,9.6,132.0,104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.32967,54.685714,16.454945,1.47033,11.718681,45.068132,43.393407,31.483516,0.859341,7.586813,103.997802,343.740659,383.263736,0.237499,0.080145,0.305822,0.387048,0.692859,0.149552,0.30284,0.845934,95.050549,97.951648,NaN

# Organize and Export

In [ ]:
# Create a new column order
ordered_columns = []
for stat in combined_stats:
    ordered_columns.append(stat)  # Add actual stat
    projected_col = f"Projected_{stat}"
    if projected_col in df.columns:
        ordered_columns.append(projected_col)  # Add projected stat if it exists

# Add any remaining columns that are not stats or projected stats
remaining_columns = [col for col in df.columns if col not in ordered_columns]
ordered_columns.extend(remaining_columns)

# Reorder the DataFrame
df = df[ordered_columns]

In [ ]:
# Get the last five columns
columns_to_move = df.columns[-5:].tolist()

# Get the remaining columns
remaining_columns = df.columns[:-5].tolist()

# Combine them with the columns_to_move first
new_column_order = columns_to_move + remaining_columns

# Reorder the DataFrame
df = df[new_column_order]

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
# Export to a specific folder
df.to_csv('../other_model_comparisons_2025/model_one.csv', index=False)

In [ ]:
# Export to a specific folder
df.to_csv('../Projection_Results/model_one.csv', index=False)